geoIpBatch:
  randomapi:
    rest:
      url: http://gturnquist-quoters.cfapps.io/api/random
  geoIp:
    service:
      url: http://www.webservicex.net/geoipservice.asmx
spring:
  datasource:
    url: jdbc:h2:file:~/h2/geo_data_db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
